export const TRIP_STATUS = {
  CREATED: 'CREATED',
  BOOKING_START: 'BOOKING_START',
  BOOKING_CLOSED: 'BOOKING_CLOSED',
  TRIP_START: 'TRIP_START',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  TRIP_BILLED: 'TRIP_BILLED',
  CLOSED: 'CLOSED',
  TERMINATED: 'TERMINATED',
};
